[workspace]
members = [
  "native/*",
]

default-members = ["native/acter"]

[workspace.dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "8b5de47acb9486c8dbbbe5764c7c97c24b6997b8"
default-features = false
features = ["rustls-tls"]

[workspace.dependencies.matrix-sdk-base]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "8b5de47acb9486c8dbbbe5764c7c97c24b6997b8"
default-features = false

[workspace.dependencies.matrix-sdk-sled]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "8b5de47acb9486c8dbbbe5764c7c97c24b6997b8"
default-features = false
features = ["crypto-store", "state-store"]

[workspace.dependencies.ruma]
git = "https://github.com/ruma/ruma"
rev = "8eea3e05490fa9a318f9ed66c3a75272e6ef0ee5"

[workspace.dependencies]
async-broadcast = "0.5"

[profile.release]
panic = "unwind"
opt-level = 2
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.