[workspace]
members = [
  "native/*",
  "util/mr_minutes"
]

default-members = ["native/acter"]

[workspace.dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "2b72df7c0611020bdfbaf5e089888d9383774c6f"
default-features = false
features = ["experimental-sliding-sync"]

[workspace.dependencies.matrix-sdk-base]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "2b72df7c0611020bdfbaf5e089888d9383774c6f"
default-features = false

[workspace.dependencies.matrix-sdk-sqlite]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "2b72df7c0611020bdfbaf5e089888d9383774c6f"
default-features = false
features = ["crypto-store", "state-store"]

[workspace.dependencies.matrix-sdk-ui]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "2b72df7c0611020bdfbaf5e089888d9383774c6f"
default-features = false
features = ["e2e-encryption"]

[workspace.dependencies.ruma]
git = "https://github.com/ruma/ruma"
rev = "5fde57460aaa71e16ac68f79376843089f9c3dfc"

[workspace.dependencies]
strum = { version = "0.24.1", features = ["derive"] }

[profile.release]
panic = "unwind"
opt-level = 2
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.