[workspace]
members = [
  "native/*",
]

default-members = ["native/effektio"]

[workspace.dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "afda63f9e2cc44e8cc7c1dca6b50264ee31a2c26"
default-features = false
features = ["rustls-tls"]

[workspace.dependencies.matrix-sdk-base]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "afda63f9e2cc44e8cc7c1dca6b50264ee31a2c26"
default-features = false

[workspace.dependencies.ruma]
git = "https://github.com/ruma/ruma"
rev = "ed100afddb5fb30f1ccf368d7e712a3a483e63bf"

[profile.release]
panic = "unwind"
opt-level = 2
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.