[workspace]
members = [
  "native/*",
]

default-members = ["native/effektio"]

[workspace.dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "ee6c0d9486640fb3d7a5442b1703da1b903577c2"
default-features = false
features = ["rustls-tls"]

[workspace.dependencies.matrix-sdk-base]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "ee6c0d9486640fb3d7a5442b1703da1b903577c2"
default-features = false

[workspace.dependencies.matrix-sdk-sled]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "ee6c0d9486640fb3d7a5442b1703da1b903577c2"
default-features = false
features = ["crypto-store", "state-store"]

[workspace.dependencies.ruma]
git = "https://github.com/ruma/ruma"
rev = "a399a4017a9f0b249ce848a652f2e4fe65435eaf"

[workspace.dependencies]
async-broadcast = "0.5"

[profile.release]
panic = "unwind"
opt-level = 2
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.