[workspace]
members = [
  "native/*",
]

default-members = ["native/effektio"]

[workspace.dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "ca30a22df014a121043e5a9c7d6cda55b7ab674a"
default-features = false
features = ["rustls-tls"]

[workspace.dependencies.matrix-sdk-base]
git = "https://github.com/matrix-org/matrix-rust-sdk"
rev = "ca30a22df014a121043e5a9c7d6cda55b7ab674a"
default-features = false

[workspace.dependencies.ruma]
git = "https://github.com/bitfriend/ruma"
rev = "537b282955736796b153ee73dae093719b8e6893"

[profile.release]
panic = "unwind"
opt-level = 2
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.