[package]
name = "effektio-core"
authors = [ "ben@effektio.org" ]
version = "0.1.0"
edition = "2021"
rust-version = "1.58"
description = "Core types and features of the effektio app"
homepage = "https://effekto.org"
repository = "https://github.com/acterglobal/a3"
license-file = "../../LICENSE.txt"

[features]
with-mocks = ["fake", "rand"]
templates = ["toml", "minijinja", "indexmap"]

[dependencies]
assign = "1.1.1"
async-broadcast = { workspace = true }
async-recursion = "1"
chrono = {version = "0.4", default-features = false, features = ["serde"]}
chrono-tz = { version = "0.5", default-features = false, features = ["serde"] }
csscolorparser = { version = "0.5.0", features = ["serde"] }
dashmap = "5.4.0"
derive-getters = "0.2.0"
enum_dispatch = "0.3.10"
derive_builder = "0.11.2"
futures = "0.3.24"
ruma-macros = { workspace = true }
serde = "1.0.136"
serde_json = "1.0.82"
serde_repr = "0.1"
thiserror = "1.0"
tracing = "0.1.37"
url = { version = "2.2.2", features = ["serde"] }

# with-mocks
fake = { version = "2.4", optional = true, features = ["derive"] }
rand = { version = "0.8", optional = true }

# templates
toml = { version = "0.7.2", optional = true, features = ["preserve_order"] }
minijinja = { version = "0.30.5", optional = true }
indexmap = { version = "1.9.2", optional = true }
async-stream = { version = "0.3.4" }

[dependencies.matrix-sdk]
workspace = true
default-features = false

[dev-dependencies]
env_logger = { version = "0.10.0" }
tokio = { version = "1", features = ["rt", "macros"]}
tracing = { version = "0.1.37", default-features = false, features = ["log"] }
anyhow = "1.0.69"

[dev-dependencies.matrix-sdk]
workspace = true
features = ["rustls-tls"]
default-features = false

[dev-dependencies.matrix-sdk-base]
workspace = true
default-features = false

