name: add artifact links to pull request and related issues
on:
  workflow_run:
    workflows: [App]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    steps:
      - name: Post artifacts links
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "Here are the artifacts for this build:"
            suffix: Enjoy
            format: name
            addTo: pull
